apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: telescope-integration-scripts-acs-efxs
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-gps-cjenkins-tenant/telescope-integration-scripts-acs/telescope-integration-scripts-acs-efxs@sha256:d90b8121ecae420215f6fa33353bbdb1a9c253b2f30c9990f495102370b9261b
        name: container-image
        resources: {}
status: {}
