apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: telescope-integration-scripts-acs-efxs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: telescope-integration-scripts-acs-efxs
    app.kubernetes.io/part-of: telescope-integration-scripts-acs
  name: telescope-integration-scregnr
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: telescope-integration-scripts-acs-efxs
    weight: 100
status: {}
