apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: telescope-integration-scripts-acs-efxs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: telescope-integration-scripts-acs-efxs
    app.kubernetes.io/part-of: telescope-integration-scripts-acs
  name: telescope-integration-scripts-acs-efxs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: telescope-integration-scripts-acs-efxs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: telescope-integration-scripts-acs-efxs
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-gps-cjenkins-tenant/telescope-integration-scripts-acs/telescope-integration-scripts-acs-efxs@sha256:62fc7ec896320a5a123d8ffaa96547f46f8e307ccb7a0303a249fc13270bf24e
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
